import { AddTenantFormState, TenantItem } from "../types/tenant.components.type";
export const DUMMY_USER = "https://sriit.ac.in/tool/plugins/images/users/4.jpg"

export const tenantsData: TenantItem[] = [
    {
        id: '123',
        propertyId: '',
        propertyName: "Room Number 1",
        propertyType: "Apartment / Flat",
        propertyAddress: "shillgaon, khopoli, maharashtra",
        propertyStatus: "Occupied",
        propertyRent: 4000,
        propertyDeposit: 7000,
        rentRecurrence: "Monthly",
        tenantImage: DUMMY_USER,
        tenantName: "Mojamil Khan",
        leaseStartDate: "01 March 2025",
        leaseEndDate: "01 March 2026",
    },
    {
        id: '124',
        propertyId: '',
        propertyName: "Room Number 2",
        propertyAddress: "shillgaon, khopoli, maharashtra",
        propertyType: "Apartment / Flat",
        propertyStatus: "Occupied",
        propertyRent: 4000,
        propertyDeposit: 7000,
        rentRecurrence: "Monthly",
        tenantImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTq4H7mPnTLV9rtqZ7_W5NeAhudM0OXP3UNNQ&s",
        tenantName: "Sarfaraz Ahmad",
        leaseStartDate: "01 March 2025",
        leaseEndDate: "01 March 2026",
    },
    {
        id: '125',
        propertyId: '',
        propertyName: "Room Number 3",
        propertyAddress: "shillgaon, khopoli, maharashtra",
        propertyType: "Apartment / Flat",
        propertyStatus: "Occupied",
        propertyRent: 3000,
        propertyDeposit: 7000,
        rentRecurrence: "Monthly",
        tenantImage: "https://sriit.ac.in/tool/plugins/images/users/4.jpg",
        tenantName: "Shafeek Shaikh",
        leaseStartDate: "01 March 2025",
        leaseEndDate: "01 March 2026",
    },
    {
        id: '126',
        propertyId: '',
        propertyName: "Room Number 2",
        propertyAddress: "mohanwadi, khopoli, maharashtra",
        propertyType: "Apartment / Flat",
        propertyStatus: "Vacant",
        propertyRent: 3500,
        propertyDeposit: 7000,
        rentRecurrence: "Monthly",
        tenantImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNR7FvvC_9X1l2xqi2rdkStAHaSRMmg89O_g&s",
        tenantName: "Sarfaraz Khan",
        leaseStartDate: "01 March 2025",
        leaseEndDate: "01 March 2026",
    },
    {
        id: '127',
        propertyId: '',
        propertyName: "Salai Land",
        propertyAddress: "salai gram, khandwa, madhya pradesh",
        propertyType: "Apartment / Flat",
        propertyStatus: "Occupied",
        propertyRent: 25000,
        propertyDeposit: 7000,
        rentRecurrence: "Monthly",
        tenantImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrJ2R9O5THIdzGHJl3RjnK2Bxzj20iYSsMQA&s",
        tenantName: "Shafeekh Khan",
        leaseStartDate: "01 March 2025",
        leaseEndDate: "01 March 2026",
    },
]

export const INITIAL_ADD_TENANT_FORM_STATE: AddTenantFormState = {
    tenantName: 'Ashish Yadav',
    email: 'ashish@gmail.com',
    phone: '9748503888',
    propertyId: '',
    deposit: '56000',
    rent: '5000',
    leaseStartDate: '2026-01-01',
    leaseEndDate: '2026-01-31',
    propertyType: "Plot / Land",
    rentRecurrence: "Monthly",
    propertyAddress: '242, New Gouri Nagar, Indore',
    note: 'Good',
};
